apiVersion: apps/v1
kind: Deployment
metadata:
  name: delta-deployment
  labels:
    app: delta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delta
  template:
    metadata:
      labels:
        app: delta
    spec:
      containers:
        - name: delta
          image: acrcloudengineer.azurecr.io/delta
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
